# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Aristotle Henderson
description: >- # this means to ignore newlines until "baseurl:"
  Aristotle Henderson's personal website, featuring information about his experience and career.
github_username: aristotleh
minimal_mistakes_skin_light: "dirt"
minimal_mistakes_skin_dark: "dark"
# search: true
url: "https://www.aristotleh.com"
repository: "aristotleh/aristotleh.github.io"

logo: "/assets/images/favicon-32x32.png"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
# permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Aristotle Henderson"
  avatar : "https://avatars.githubusercontent.com/u/53080395"
  bio    : "I'm a fourth-year computer science student at UCLA with experience across industry and academia."
  location: "Los Angeles, CA"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/aristotleh"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/aristotleh"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/aristotleh"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/aristotleh"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

atom_feed:
  hide: true